# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_options=b'\n\013sr.grpc.genB\017CalculatorProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"3\n\x15\x41rithmeticOpArguments\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x05\"!\n\x12\x41rithmeticOpResult\x12\x0b\n\x03res\x18\x01 \x01(\x05\"W\n\x1c\x43omplexArithmeticOpArguments\x12)\n\x06optype\x18\x01 \x01(\x0e\x32\x19.calculator.OperationType\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\x01\"(\n\x19\x43omplexArithmeticOpResult\x12\x0b\n\x03res\x18\x01 \x01(\x01*3\n\rOperationType\x12\x07\n\x03SUM\x10\x00\x12\x07\n\x03\x41VG\x10\x01\x12\x07\n\x03MIN\x10\x02\x12\x07\n\x03MAX\x10\x03\x32\xa9\x01\n\nCalculator\x12J\n\x03\x41\x64\x64\x12!.calculator.ArithmeticOpArguments\x1a\x1e.calculator.ArithmeticOpResult\"\x00\x12O\n\x08Subtract\x12!.calculator.ArithmeticOpArguments\x1a\x1e.calculator.ArithmeticOpResult\"\x00\x32{\n\x12\x41\x64vancedCalculator\x12\x65\n\x10\x43omplexOperation\x12(.calculator.ComplexArithmeticOpArguments\x1a%.calculator.ComplexArithmeticOpResult\"\x00\x42 \n\x0bsr.grpc.genB\x0f\x43\x61lculatorProtoP\x01\x62\x06proto3'
)

_OPERATIONTYPE = _descriptor.EnumDescriptor(
  name='OperationType',
  full_name='calculator.OperationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUM', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AVG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MIN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MAX', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=251,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONTYPE)

OperationType = enum_type_wrapper.EnumTypeWrapper(_OPERATIONTYPE)
SUM = 0
AVG = 1
MIN = 2
MAX = 3



_ARITHMETICOPARGUMENTS = _descriptor.Descriptor(
  name='ArithmeticOpArguments',
  full_name='calculator.ArithmeticOpArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arg1', full_name='calculator.ArithmeticOpArguments.arg1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arg2', full_name='calculator.ArithmeticOpArguments.arg2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=83,
)


_ARITHMETICOPRESULT = _descriptor.Descriptor(
  name='ArithmeticOpResult',
  full_name='calculator.ArithmeticOpResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='calculator.ArithmeticOpResult.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=118,
)


_COMPLEXARITHMETICOPARGUMENTS = _descriptor.Descriptor(
  name='ComplexArithmeticOpArguments',
  full_name='calculator.ComplexArithmeticOpArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='optype', full_name='calculator.ComplexArithmeticOpArguments.optype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='calculator.ComplexArithmeticOpArguments.args', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=207,
)


_COMPLEXARITHMETICOPRESULT = _descriptor.Descriptor(
  name='ComplexArithmeticOpResult',
  full_name='calculator.ComplexArithmeticOpResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='calculator.ComplexArithmeticOpResult.res', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=249,
)

_COMPLEXARITHMETICOPARGUMENTS.fields_by_name['optype'].enum_type = _OPERATIONTYPE
DESCRIPTOR.message_types_by_name['ArithmeticOpArguments'] = _ARITHMETICOPARGUMENTS
DESCRIPTOR.message_types_by_name['ArithmeticOpResult'] = _ARITHMETICOPRESULT
DESCRIPTOR.message_types_by_name['ComplexArithmeticOpArguments'] = _COMPLEXARITHMETICOPARGUMENTS
DESCRIPTOR.message_types_by_name['ComplexArithmeticOpResult'] = _COMPLEXARITHMETICOPRESULT
DESCRIPTOR.enum_types_by_name['OperationType'] = _OPERATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArithmeticOpArguments = _reflection.GeneratedProtocolMessageType('ArithmeticOpArguments', (_message.Message,), {
  'DESCRIPTOR' : _ARITHMETICOPARGUMENTS,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.ArithmeticOpArguments)
  })
_sym_db.RegisterMessage(ArithmeticOpArguments)

ArithmeticOpResult = _reflection.GeneratedProtocolMessageType('ArithmeticOpResult', (_message.Message,), {
  'DESCRIPTOR' : _ARITHMETICOPRESULT,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.ArithmeticOpResult)
  })
_sym_db.RegisterMessage(ArithmeticOpResult)

ComplexArithmeticOpArguments = _reflection.GeneratedProtocolMessageType('ComplexArithmeticOpArguments', (_message.Message,), {
  'DESCRIPTOR' : _COMPLEXARITHMETICOPARGUMENTS,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.ComplexArithmeticOpArguments)
  })
_sym_db.RegisterMessage(ComplexArithmeticOpArguments)

ComplexArithmeticOpResult = _reflection.GeneratedProtocolMessageType('ComplexArithmeticOpResult', (_message.Message,), {
  'DESCRIPTOR' : _COMPLEXARITHMETICOPRESULT,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.ComplexArithmeticOpResult)
  })
_sym_db.RegisterMessage(ComplexArithmeticOpResult)


DESCRIPTOR._options = None

_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='calculator.Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=305,
  serialized_end=474,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='calculator.Calculator.Add',
    index=0,
    containing_service=None,
    input_type=_ARITHMETICOPARGUMENTS,
    output_type=_ARITHMETICOPRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Subtract',
    full_name='calculator.Calculator.Subtract',
    index=1,
    containing_service=None,
    input_type=_ARITHMETICOPARGUMENTS,
    output_type=_ARITHMETICOPRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR


_ADVANCEDCALCULATOR = _descriptor.ServiceDescriptor(
  name='AdvancedCalculator',
  full_name='calculator.AdvancedCalculator',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=476,
  serialized_end=599,
  methods=[
  _descriptor.MethodDescriptor(
    name='ComplexOperation',
    full_name='calculator.AdvancedCalculator.ComplexOperation',
    index=0,
    containing_service=None,
    input_type=_COMPLEXARITHMETICOPARGUMENTS,
    output_type=_COMPLEXARITHMETICOPRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADVANCEDCALCULATOR)

DESCRIPTOR.services_by_name['AdvancedCalculator'] = _ADVANCEDCALCULATOR

# @@protoc_insertion_point(module_scope)
